### ISSUE TITLE
Add scripts.js to gulp watch config. 

### ISSUE THREAD

**Issue by runningCoder81** [rosemont-media/RM-WordPress-Theme#25]
Hook up gulp to watch for changes on scripts.js

**Comment by djmisha** [comment]
Should already be in config, just need to turn on.  Maybe we compile final js into another file, but not minified

**Comment by djmisha** [comment]
![Screen Shot 2019-10-12 at 6 54 06 AM](https://user-images.githubusercontent.com/4982902/66702535-9be59800-ecbd-11e9-82fb-a3c33c14ab22.png)
activate like this, will refresh the browser when you save a JS file

**Comment by djmisha** [comment]
added to gulpfile.js
